name: gmp
description: Gestor monitoreo público.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #camera:
  path_provider:
  path:
  image_picker:

  shared_preferences:  

  cupertino_icons: ^0.1.3
  http: any
  skeleton_text:
  carousel_slider: ^2.3.1
  flutter_signin_button: ^1.1.0
  google_sign_in: ^4.5.9
  change_app_package_name: ^0.1.2
  badges: ^1.1.6
  flutter_slidable: ^0.5.7
  flutter_web_browser: ^0.14.0
  google_maps_flutter: ^2.0.5
  location: ^2.3.5
  flutter_polyline_points: ^1.0.0
  geolocator: ^5.3.1
  charts_flutter: ^0.11.0
  #graphic: ^0.3.0
  flutter_echarts: ^1.5.0
  pie_chart: ^3.1.1
  firebase_auth: ^1.1.4
  provider: ^4.3.3
  firebase_core: ^1.3.0
  flutter_launcher_icons: ^0.7.4
  #flutter_launcher_icons: ^0.9.0
  #apple_sign_in: ^0.1.0
  the_apple_sign_in: ^1.1.1
  fluttertoast: ^7.1.8
  firebase_messaging: ^10.0.0
  flutter_secure_storage: ^4.2.0
  #sign_in_with_apple: ^3.0.0
  geocoding: ^2.0.1
  sleek_circular_slider: ^2.0.1
  #motion_tab_bar: ^0.1.5
  syncfusion_flutter_charts: ^19.2.62
  line_icons: ^2.0.1
  md2_tab_indicator: ^1.0.2
  flutter_sparkline: ^0.1.0
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  dio: ^4.0.6
  motion_toast: ^1.2.0
  blurry_modal_progress_hud: ^1.0.3
  expansion_card: ^0.1.0
  sweetalert: ^0.0.1
  url_launcher: ^6.1.2
  shimmer: ^2.0.0
  flutter_pdfview: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/images/icon.jpg'
  android: "launcher_icon"
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
        - assets/images/